import type { Metadata } from "next";

export const siteConfig = {
    name: "Panthar InfoHub",
    description: "Panthar InfoHub is a leading technology consultancy and product development company based in Jhansi, India. We specialize in mobile and web app development, AI and machine learning solutions, cloud computing, safety technology, and IT services tailored to meet the unique needs of businesses and individuals.",
    url: "https://pantharinfohub.com",
    ogImage: "https://pantharinfohub.com/assets/logo.png",
    companyName: "Panthar InfoHub Pvt. Ltd.",
    region: "Jhansi, Uttar Pradesh, India",
    socials: {
        website: "https://pantharinfohub.com",
        linkedin: "https://www.linkedin.com/company/panthar-infohub/",
        instagram: "https://www.instagram.com/panthar.infohub?igsh=ZWxsejBtaGF2dmhh",
        twitter: "",
        facebook: "",
        youtube: "",
    },
    contact: {
        email: "connect@pantharinfohub.com",
        phone: "+91 6393957916",
        address: "RISE Incubation, Nagar Nigam Premises, Elite Square, Civil Lines, Jhansi (UP) - 284001",
    },
};

export const metadata: Metadata = {
    title: `${siteConfig.name} - Your Partner in Innovative Tech Solutions and Consultancy`,
    description: siteConfig.description,
    keywords: [
        "Panthar InfoHub",
        "Panthar Infohub Pvt. Ltd.",
        "panthar infohub",
        "panthar",
        "tech consultancy",
        "mobile app development in Jhansi",
        "web app development company",
        "AI integration services",
        "AI solutions company",
        "cloud computing services",
        "cloud computing consultancy",
        "software development company Jhansi",
        "software solutions Uttar Pradesh",
        "IoT solutions",
        "custom software development",
        "product-based company",
        "mobile app company in India",
        "tech innovation company",
        "website design in Jhansi",
        "website development company Uttar Pradesh",
        "IT services Jhansi",
        "IT consultancy India",
        "digital transformation solutions",
        "AI-powered apps",
        "safety apps for emergencies",
        "innovative technology Jhansi",
        "tech services India",
        "full-stack development company",
    ],
    authors: [{ name: siteConfig.companyName }],
    robots: "index, follow",
    openGraph: {
        title: `${siteConfig.name} - Revolutionizing Tech Services and Solutions`,
        description: siteConfig.description,
        url: siteConfig.url,
        siteName: siteConfig.name,
        images: [
            {
                url: siteConfig.ogImage,
                width: 1200,
                height: 630,
            },
        ],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: `${siteConfig.name} - Leading Tech Consultancy in India`,
        description: siteConfig.description,
        images: [siteConfig.ogImage],
    },
    other: {
        company: siteConfig.name,
        region: siteConfig.region,
        charset: "UTF-8",
        "linkedin:title": `${siteConfig.name} - Innovating Tech for the Future`,
        "linkedin:description": siteConfig.description,
        "linkedin:image": siteConfig.ogImage,
        "instagram:title": `${siteConfig.name} - Innovative Tech Solutions`,
        "instagram:description": siteConfig.description,
        "instagram:image": siteConfig.ogImage,
    },
};
